[webservers]
web1 ansible_host=web1.example.com ansible_user=example ansible_ssh_private_key_file=~/.ssh/id_rsa_web1
web2 ansible_host=web2.example.com ansible_user=example ansible_ssh_private_key_file=~/.ssh/id_rsa_web2

; RHEL issues
[webservers:vars]
ansible_python_interpreter=/usr/bin/python3

[dbservers]
db1 ansible_host=db1.example.com ansible_user=example ansible_ssh_private_key_file=~/.ssh/id_rsa_db1
db2 ansible_host=db2.example.com ansible_user=example ansible_ssh_private_key_file=~/.ssh/id_rsa_db2
